# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
 
              
            
name: main_test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: self-hosted
    #runs-on: ubuntu-latest
 # Service containers to run with `runner-job`
   # services:
      # Label used to access the service container
    #  redis:
    #    # Docker Hub image
     #   image: redis
      #  # Set health checks to wait until redis has started
       # options: >-
        #  --health-cmd "redis-cli ping"
         # --health-interval 10s
          #--health-timeout 5s
          #--health-retries 5
        #ports:
          # Maps port 6379 on service container to the host
         # - 6379:6379

    steps:   
    - uses: actions/checkout@v3 
    - name: Setup .NET
      uses: actions/setup-dotnet@v3      
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test      
      run: dotnet test --no-build --verbosity normal
